name: Documentation

on:
  push: # OR relationships
    # branches:
    #   - dev         # trigger：only when pushed to dev branch (dev)
    tags: ['*']      # trigger：when any git tag (stable)
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Julia
        uses: julia-actions/setup-julia@v3
        with:
          version: '1.12'

      - name: Cache Julia artifacts
        uses: julia-actions/cache@v3

      - name: Build and Deploy Documentation
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          julia --project=docs/ -e '
            using Pkg
            Pkg.develop(PackageSpec(path=pwd()))
            Pkg.instantiate()
            include("docs/make.jl")'